// Mock data for development - will be replaced with Oracle DB connection
import { Product, Recipe, ShoppingListItem } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Milk',
    category: 'dairy',
    quantity: 1,
    unit: 'liters',
    minQuantity: 2,
    expirationDate: '2026-01-18',
    location: 'fridge',
    createdAt: '2026-01-01',
    updatedAt: '2026-01-10',
  },
  {
    id: '2',
    name: 'Eggs',
    category: 'dairy',
    quantity: 12,
    unit: 'pieces',
    minQuantity: 6,
    location: 'fridge',
    createdAt: '2026-01-05',
    updatedAt: '2026-01-10',
  },
  {
    id: '3',
    name: 'Chicken Breast',
    category: 'meat',
    quantity: 0.5,
    unit: 'kg',
    minQuantity: 1,
    expirationDate: '2026-01-15',
    location: 'fridge',
    createdAt: '2026-01-08',
    updatedAt: '2026-01-10',
  },
  {
    id: '4',
    name: 'Spinach',
    category: 'vegetables',
    quantity: 200,
    unit: 'grams',
    minQuantity: 100,
    expirationDate: '2026-01-14',
    location: 'fridge',
    createdAt: '2026-01-09',
    updatedAt: '2026-01-10',
  },
  {
    id: '5',
    name: 'Frozen Pizza',
    category: 'frozen',
    quantity: 2,
    unit: 'pieces',
    minQuantity: 1,
    location: 'freezer',
    createdAt: '2026-01-02',
    updatedAt: '2026-01-10',
  },
  {
    id: '6',
    name: 'Orange Juice',
    category: 'beverages',
    quantity: 0.5,
    unit: 'liters',
    minQuantity: 1,
    expirationDate: '2026-01-20',
    location: 'fridge',
    createdAt: '2026-01-06',
    updatedAt: '2026-01-10',
  },
  {
    id: '7',
    name: 'Butter',
    category: 'dairy',
    quantity: 100,
    unit: 'grams',
    minQuantity: 200,
    expirationDate: '2026-02-01',
    location: 'fridge',
    createdAt: '2026-01-01',
    updatedAt: '2026-01-10',
  },
  {
    id: '8',
    name: 'Apples',
    category: 'fruits',
    quantity: 5,
    unit: 'pieces',
    minQuantity: 3,
    location: 'fridge',
    createdAt: '2026-01-07',
    updatedAt: '2026-01-10',
  },
];

export const mockRecipes: Recipe[] = [
  {
    id: '1',
    name: 'Scrambled Eggs',
    description: 'Classic fluffy scrambled eggs with butter',
    ingredients: [
      { name: 'Eggs', quantity: 3, unit: 'pieces', productId: '2' },
      { name: 'Butter', quantity: 20, unit: 'grams', productId: '7' },
      { name: 'Milk', quantity: 30, unit: 'ml', productId: '1' },
      { name: 'Salt', quantity: 1, unit: 'pinch' },
    ],
    instructions: [
      'Crack eggs into a bowl and whisk with milk',
      'Heat butter in a pan over medium-low heat',
      'Add eggs and stir gently with a spatula',
      'Remove from heat when slightly underdone',
      'Season with salt and serve immediately',
    ],
    prepTime: 5,
    cookTime: 5,
    servings: 2,
    tags: ['breakfast', 'quick', 'easy'],
    createdAt: '2026-01-01',
  },
  {
    id: '2',
    name: 'Chicken Spinach Salad',
    description: 'Healthy grilled chicken salad with fresh spinach',
    ingredients: [
      { name: 'Chicken Breast', quantity: 200, unit: 'grams', productId: '3' },
      { name: 'Spinach', quantity: 100, unit: 'grams', productId: '4' },
      { name: 'Olive Oil', quantity: 2, unit: 'tbsp' },
      { name: 'Lemon Juice', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Season chicken with salt and pepper',
      'Grill chicken for 6-7 minutes each side',
      'Let chicken rest, then slice',
      'Arrange spinach on plates',
      'Top with sliced chicken and drizzle with olive oil and lemon',
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    tags: ['lunch', 'healthy', 'protein'],
    createdAt: '2026-01-02',
  },
  {
    id: '3',
    name: 'Fresh Apple Smoothie',
    description: 'Refreshing apple and milk smoothie',
    ingredients: [
      { name: 'Apples', quantity: 2, unit: 'pieces', productId: '8' },
      { name: 'Milk', quantity: 200, unit: 'ml', productId: '1' },
      { name: 'Honey', quantity: 1, unit: 'tbsp', optional: true },
    ],
    instructions: [
      'Core and chop apples into chunks',
      'Add apples and milk to blender',
      'Blend until smooth',
      'Add honey if desired',
      'Serve cold',
    ],
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    tags: ['drinks', 'healthy', 'quick'],
    createdAt: '2026-01-03',
  },
];

export const mockShoppingList: ShoppingListItem[] = [
  {
    id: '1',
    productId: '1',
    name: 'Milk',
    quantity: 2,
    unit: 'liters',
    category: 'dairy',
    checked: false,
    addedAt: '2026-01-10',
  },
  {
    id: '2',
    productId: '7',
    name: 'Butter',
    quantity: 250,
    unit: 'grams',
    category: 'dairy',
    checked: false,
    addedAt: '2026-01-10',
  },
];
