// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "List inventory products",
  description: "List the signed-in user's food inventory products. Optionally filter by name search, category, location, or only items at or below their minimum quantity.",
  inputSchema: {
    search: z.string().trim().min(1).optional().describe("Case-insensitive product name filter."),
    category: z.string().trim().min(1).optional().describe("Exact category name."),
    location: z.string().trim().min(1).optional().describe("Exact storage location name."),
    lowStockOnly: z.boolean().optional().describe("Only return products at or below their minimum quantity."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, category, location, lowStockOnly, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("products").select("id,name,category,location,quantity,unit,min_quantity,expiration_date,tags,notes").order("name").limit(limit ?? 50);
    if (search) query = query.ilike("name", `%${search}%`);
    if (category) query = query.eq("category", category);
    if (location) query = query.eq("location", location);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).filter(
      (row) => !lowStockOnly || Number(row.quantity) <= Number(row.min_quantity)
    );
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { products: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/upsert-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var upsert_product_default = defineTool2({
  name: "upsert_product",
  title: "Create or update a product",
  description: "Create a new inventory product, or update an existing one when productId is given. Only the provided fields are changed.",
  inputSchema: {
    productId: z2.string().uuid().optional().describe("Existing product id. Omit to create a new product."),
    name: z2.string().trim().min(1).optional().describe("Product name (required when creating)."),
    category: z2.string().trim().min(1).optional(),
    location: z2.string().trim().min(1).optional(),
    quantity: z2.number().min(0).optional(),
    unit: z2.string().trim().min(1).optional(),
    minQuantity: z2.number().min(0).optional(),
    expirationDate: z2.string().trim().min(1).nullable().optional().describe("ISO date (YYYY-MM-DD) or null to clear."),
    notes: z2.string().nullable().optional(),
    tags: z2.array(z2.string().trim().min(1)).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const fields = {};
    if (input.name !== void 0) fields.name = input.name;
    if (input.category !== void 0) fields.category = input.category;
    if (input.location !== void 0) fields.location = input.location;
    if (input.quantity !== void 0) fields.quantity = input.quantity;
    if (input.unit !== void 0) fields.unit = input.unit;
    if (input.minQuantity !== void 0) fields.min_quantity = input.minQuantity;
    if (input.expirationDate !== void 0) fields.expiration_date = input.expirationDate;
    if (input.notes !== void 0) fields.notes = input.notes;
    if (input.tags !== void 0) fields.tags = input.tags;
    if (input.productId) {
      if (Object.keys(fields).length === 0) {
        return { content: [{ type: "text", text: "No fields to update" }], isError: true };
      }
      const { data: data2, error: error2 } = await supabase.from("products").update(fields).eq("id", input.productId).select().maybeSingle();
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      if (!data2) return { content: [{ type: "text", text: "Product not found" }], isError: true };
      return { content: [{ type: "text", text: JSON.stringify(data2) }], structuredContent: { product: data2 } };
    }
    if (!input.name) {
      return { content: [{ type: "text", text: "name is required when creating a product" }], isError: true };
    }
    const { data, error } = await supabase.from("products").insert({ ...fields, name: input.name, user_id: ctx.getUserId() }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { product: data } };
  }
});

// src/lib/mcp/tools/list-shopping-list.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_shopping_list_default = defineTool3({
  name: "list_shopping_list",
  title: "List shopping list items",
  description: "List the signed-in user's shopping list items, optionally only the unchecked ones.",
  inputSchema: {
    uncheckedOnly: z3.boolean().optional().describe("Only return items that are not yet checked off.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ uncheckedOnly }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("shopping_list_items").select("id,name,quantity,unit,category,checked,added_at").order("category", { ascending: true }).order("name", { ascending: true });
    if (uncheckedOnly) query = query.eq("checked", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/add-shopping-list-item.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var add_shopping_list_item_default = defineTool4({
  name: "add_shopping_list_item",
  title: "Add a shopping list item",
  description: "Add an item to the signed-in user's shopping list.",
  inputSchema: {
    name: z4.string().trim().min(1).describe("Item name."),
    quantity: z4.number().min(0).optional().describe("Quantity to buy (default 1)."),
    unit: z4.string().trim().min(1).optional().describe('Unit, e.g. \u05D9\u05D7\u05F3, \u05E7"\u05D2.'),
    category: z4.string().trim().min(1).optional().describe("Category used for grouping and sorting."),
    productId: z4.string().uuid().optional().describe("Link to an existing inventory product.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, quantity, unit, category, productId }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("shopping_list_items").insert({
      user_id: ctx.getUserId(),
      name,
      quantity: quantity ?? 1,
      ...unit ? { unit } : {},
      ...category ? { category } : {},
      ...productId ? { product_id: productId } : {}
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { item: data } };
  }
});

// src/lib/mcp/tools/list-recipes.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_recipes_default = defineTool5({
  name: "list_recipes",
  title: "List recipes",
  description: "List the signed-in user's recipes with ingredients and instructions. Optionally filter by name search or tag.",
  inputSchema: {
    search: z5.string().trim().min(1).optional().describe("Case-insensitive recipe name filter."),
    tag: z5.string().trim().min(1).optional().describe("Only recipes carrying this tag."),
    limit: z5.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, tag, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("recipes").select("id,name,description,ingredients,instructions,prep_time,cook_time,servings,tags,is_public").order("name").limit(limit ?? 25);
    if (search) query = query.ilike("name", `%${search}%`);
    if (tag) query = query.contains("tags", [tag]);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { recipes: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-calendar-events.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_calendar_events_default = defineTool6({
  name: "list_calendar_events",
  title: "List calendar events",
  description: "List the signed-in user's monthly calendar events within a date range (inclusive).",
  inputSchema: {
    from: z6.string().trim().min(1).describe("Start date, ISO YYYY-MM-DD."),
    to: z6.string().trim().min(1).describe("End date, ISO YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("monthly_calendar_events").select("id,date,description,time_display,sort_order").gte("date", from).lte("date", to).order("date").order("sort_order");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { events: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/add-calendar-event.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^3.25.76";
var add_calendar_event_default = defineTool7({
  name: "add_calendar_event",
  title: "Add a calendar event",
  description: "Add an event or task to a specific day in the signed-in user's monthly calendar.",
  inputSchema: {
    date: z7.string().trim().min(1).describe("Event date, ISO YYYY-MM-DD."),
    description: z7.string().trim().min(1).describe("What the event is."),
    timeDisplay: z7.string().trim().regex(/^\d{2}:\d{2}(-\d{2}:\d{2})?$/).optional().describe("Optional time as HH:MM or HH:MM-HH:MM.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ date, description, timeDisplay }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { count } = await supabase.from("monthly_calendar_events").select("id", { count: "exact", head: true }).eq("date", date);
    const { data, error } = await supabase.from("monthly_calendar_events").insert({
      user_id: ctx.getUserId(),
      date,
      description,
      sort_order: count ?? 0,
      ...timeDisplay ? { time_display: timeDisplay } : {}
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { event: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "khulhorabkxhnydxenik";
var mcp_default = defineMcp({
  name: "home-stock-manager",
  title: "Home Stock Manager",
  version: "0.1.0",
  instructions: "Tools for the Home Stock Manager app (Hebrew household food inventory). Read and update the signed-in user's pantry inventory, shopping list, recipes, and monthly calendar events. Dates are ISO YYYY-MM-DD; event times use HH:MM or HH:MM-HH:MM.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_products_default,
    upsert_product_default,
    list_shopping_list_default,
    add_shopping_list_item_default,
    list_recipes_default,
    list_calendar_events_default,
    add_calendar_event_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
